name: CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: npm install
        run: npm install
      - name: build
        run: npm run build
      - name: GitHub Pages Deploy
        uses: maxheld83/ghpages@v0.2.1
        with:
          secrets: ${{ secrets.GH_PAT }}
        env:
          BUILD_DIR: "public/"
